
var equipment_list = [
    //1
    { name: 'left', category: 'left', label: "ムチ", price: 100, lv: 1, str: 10, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "ナイフ", price: 100, lv: 1, str: 10, vit: 0, spd: 0 },
    { name: 'outer', category: 'outer', label: "上着", price: 100, lv: 1, str: 0, vit: 5, spd: 0 },
    { name: 'pants', category: 'pants', label: "パンツ", price: 100, lv: 1, str: 0, vit: 5, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "帽子", price: 100, lv: 1, str: 0, vit: 5, spd: 0 },
    { name: 'ring', category: 'ring', label: "指輪", price: 100, lv: 1, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "腕輪", price: 100, lv: 1, str: 0, vit: 0, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "首輪", price: 100, lv: 1, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "靴", price: 100, lv: 1, str: 0, vit: 0, spd: 5 },
    //2
    { name: 'left', category: 'left', label: "ロングソード", price: 200, lv: 2, str: 20, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "レザーバックル", price: 200, lv: 2, str: 0, vit: 10, spd: 0 },
    { name: 'outer', category: 'outer', label: "レザーチュニック", price: 200, lv: 2, str: 0, vit: 10, spd: 0 },
    { name: 'pants', category: 'pants', label: "レザーパンツ", price: 200, lv: 2, str: 0, vit: 10, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "レザーガード", price: 200, lv: 2, str: 0, vit: 10, spd: 0 },
    { name: 'ring', category: 'ring', label: "聖鉄の指輪", price: 200, lv: 2, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "レザーグローブ", price: 200, lv: 2, str: 5, vit: 5, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "冒険のお守り", price: 200, lv: 2, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "レザーブーツ", price: 200, lv: 2, str: 0, vit: 0, spd: 10 },
    //3
    { name: 'left', category: 'left', label: "バスタードソード", price: 300, lv: 3, str: 30, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "タワーシールド", price: 300, lv: 3, str: 0, vit: 15, spd: 0 },
    { name: 'outer', category: 'outer', label: "アイアンプレート", price: 300, lv: 3, str: 0, vit: 15, spd: 0 },
    { name: 'pants', category: 'pants', label: "アイアングリーブス", price: 300, lv: 3, str: 0, vit: 15, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "アイアンヘルム", price: 300, lv: 3, str: 0, vit: 15, spd: 0 },
    { name: 'ring', category: 'ring', label: "琥珀の指輪", price: 300, lv: 3, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "アイアンガントレット", price: 300, lv: 3, str: 5, vit: 10, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "シルバークロス", price: 300, lv: 3, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "アイアンカレガ", price: 300, lv: 3, str: 0, vit: 10, spd: -5 },
    //4
    { name: 'left', category: 'left', label: "ヴァイパー", price: 400, lv: 4, str: 30, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "ゴーシュ", price: 400, lv: 4, str: 30, vit: 0, spd: 0 },
    { name: 'outer', category: 'outer', label: "砂塵のマント", price: 400, lv: 4, str: 0, vit: 20, spd: 5 },
    { name: 'pants', category: 'pants', label: "砂塵のパンツ", price: 400, lv: 4, str: 0, vit: 20, spd: 5 },
    { name: 'helmet', category: 'helmet', label: "砂塵のフード", price: 400, lv: 4, str: 0, vit: 10, spd: 5 },
    { name: 'ring', category: 'ring', label: "小鬼の骨輪", price: 400, lv: 4, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "砂塵の小手", price: 400, lv: 4, str: 10, vit: 10, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "鬼の呼び笛", price: 400, lv: 4, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "砂塵の靴", price: 400, lv: 4, str: 0, vit: 0, spd: 40 },
    //5
    { name: 'left', category: 'left', label: "クマの爪", price: 500, lv: 5, str: 40, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "クマの爪", price: 500, lv: 5, str: 40, vit: 0, spd: 0 },
    { name: 'outer', category: 'outer', label: "格闘王の上着", price: 500, lv: 5, str: 0, vit: 25, spd: 0 },
    { name: 'pants', category: 'pants', label: "格闘王のパンツ", price: 500, lv: 5, str: 0, vit: 25, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "格闘王の鉢巻", price: 500, lv: 5, str: 0, vit: 25, spd: 0 },
    { name: 'ring', category: 'ring', label: "勝利の指輪", price: 500, lv: 5, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "気の腕輪", price: 500, lv: 5, str: 20, vit: 20, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "見破りの眼", price: 500, lv: 5, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "格闘王の靴", price: 500, lv: 5, str: 0, vit: 0, spd: 50 },
    //6
    { name: 'left', category: 'left', label: "オブシディアンソード", price: 600, lv: 6, str: 60, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "オブシディアンシールド", price: 600, lv: 6, str: 0, vit: 20, spd: 0 },
    { name: 'outer', category: 'outer', label: "オブシディアンメイル", price: 600, lv: 6, str: 0, vit: 30, spd: 0 },
    { name: 'pants', category: 'pants', label: "オブシディアングリーブス", price: 600, lv: 6, str: 0, vit: 30, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "オブシディアンヘルム", price: 600, lv: 6, str: 0, vit: 30, spd: 0 },
    { name: 'ring', category: 'ring', label: "魔封じの指輪", price: 600, lv: 6, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "オブシディアンガントレット", price: 600, lv: 6, str: 0, vit: 30, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "暗黒の翼", price: 600, lv: 6, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "オブシディアンブーツ", price: 600, lv: 6, str: 0, vit: 20, spd: 40 },
    //7
    { name: 'left', category: 'left', label: "フランベルジュ", price: 700, lv: 7, str: 70, vit: 0, spd: 0 },
    { name: 'right', category: 'right', label: "フレイムシールド", price: 700, lv: 7, str: 20, vit: 40, spd: 0 },
    { name: 'outer', category: 'outer', label: "ドラゴニックメイル", price: 700, lv: 7, str: 0, vit: 35, spd: 0 },
    { name: 'pants', category: 'pants', label: "ドラゴニックレギンス", price: 700, lv: 7, str: 0, vit: 35, spd: 0 },
    { name: 'helmet', category: 'helmet', label: "ドラゴニックヘルム", price: 700, lv: 7, str: 0, vit: 35, spd: 0 },
    { name: 'ring', category: 'ring', label: "炎帝の爪", price: 700, lv: 7, str: 0, vit: 0, spd: 0 },
    { name: 'brcelet', category: 'brcelet', label: "ドラゴニックガントレット", price: 700, lv: 7, str: 30, vit: 10, spd: 0 },
    { name: 'necklace', category: 'necklace', label: "龍族の証", price: 700, lv: 7, str: 0, vit: 0, spd: 0 },
    { name: 'shoes', category: 'shoes', label: "ドラゴニックサバトン", price: 700, lv: 7, str: 0, vit: 0, spd: 70 },
];